### ISSUE TITLE
Failed to push - have to log into git in terminal

### ISSUE THREAD

**Issue by findingpixels** [ReviewNB/jupyterlab-gitplus#10] opened 2020-11-08 04:54 UTC
Super new to Jupyter Lab. 
Got it up and running on a vm running Ubuntu. 
Got GitPlus working - which was great! 
Setup JupyterLab as a service to start automatically and tested.
Almost everything works on bootup. But I cannot push to Github repo. 
I double checked that I saved the Github token correctly.

A possible solution that I got to work. - I opened a new terminal window in Jupyter Lab and logged into git there. Then, when I used GitPlus to push - it would go through successfully. 

It seems like GitPlus is not using the access token, or I've broken something related to that. 

This is the error that GitPlus shows : 
Failure
Failed to create/push commit. Check Jupyter logs for error.

**Comment by amit1rrr** [comment] 2020-11-08 13:56
> Check Jupyter logs for error.

Can you check the jupyter terminal for any errors? If yes, please paste a screenshot or something here.

**Comment by amit1rrr** [comment] 2020-11-08 14:00
> A possible solution that I got to work. - I opened a new terminal window in Jupyter Lab and logged into git there. Then, when I used GitPlus to push - it would go through successfully.

That's interesting. What do you mean by "logged into git"?

**Comment by findingpixels** [comment] 2020-11-08 14:48
I’m not at my computer, so I can’t dig into logs yet.
In Jupiter, opened a new terminal tab and entered:
git push

It asked for my GitHub username and password and went through the push process.
After that, I could use GitPlus to push files to same GitHub repo.

**Comment by amit1rrr** [comment] 2020-11-09 05:21
If it's possible to reproduce, I'd like to look at the failure logs.

**Comment by amit1rrr** [comment] 2021-07-09 12:28
Closing due to lack of details. We've also made a lot of improvements since this issue was opened. Any likely problems might have gotten fixed already. But if you see this problem again, feel free to reopen and we'll take a look.

**Closed by amit1rrr** 2021-07-09 12:28 UTC
